package constants

const (
	KCurHero = "hero"
)

const (
	DEFAULT_SCENE  = 1
	DEFAULT_SCENE2 = 2

	MONSTER_TYPE_NORMAL = 0
	MONSTER_TYPE_NPC    = 1

	SCENE_AOI_GRID_SIZE = 60
)

const (
	ATTR_TYPE_STRENGTH = iota
	ATTR_TYPE_AGILITY
	ATTR_TYPE_INTELLIGENCE
)

const (
	ENTITY_TYPE_HERO int = iota
	ENTITY_TYPE_MONSTER
	ENTITY_TYPE_SPELL
)

type ActionState int

const (
	ACTION_STATE_IDLE ActionState = iota
	ACTION_STATE_WALK
	ACTION_STATE_RUN
	ACTION_STATE_CHASE  //追击
	ACTION_STATE_ESCAPE //逃跑
	ACTION_STATE_ATTACK
	ACTION_STATE_DIE
)

type BEHAVIOR int

// AI行为状态
const (
	BEHAVIOR_STATE_IDLE BEHAVIOR = iota
	BEHAVIOR_STATE_ATTACK
	BEHAVIOR_STATE_ESCAPE
	BEHAVIOR_STATE_RETURN
	BEHAVIOR_STATE_FOLLOW
	BEHAVIOR_STATE_LOOP_WALKER
)
